// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nopeynuwhbawauessiut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcGV5bnV3aGJhd2F1ZXNzaXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzA4MTIsImV4cCI6MjA3MjU0NjgxMn0.CwpkLXxWMhyQNJWXxl6DCxJ-QDuIciRMlX3YtCEzriE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});